{"asctime": "2024-04-04 T14:29:19+0530", "name": "ErrorLogger", "levelname": "ERROR", "message": "An Error Occured: 'Call 5.wav'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\main.py\", line 285, in pipeline_after_transcription\n    self.power_bi_report_main_helper(\n  File \"C:\\Celebal data\\Telecom Egypt\\fastapi\\Telecom%20Egypt%20Internal\\main.py\", line 447, in power_bi_report_main_helper\n    call_dict[audio_file][\"language\"] = language\n    ~~~~~~~~~^^^^^^^^^^^^\nKeyError: 'Call 5.wav'", "location": "main.py - pipeline_after_transcription"}
