{"asctime": "2024-06-08 T15:00:36+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Celebal data\\Clients\\Telecom Egypt\\Extract summary\\summary_pipeline\\main.py\", line 304, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\audio\\audio.py\", line 45, in audio_processing\n    sound = AudioSegment.from_mp3(input_path)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\pydub\\audio_segment.py\", line 796, in from_mp3\n    return cls.from_file(file, 'mp3', parameters=parameters)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\pydub\\audio_segment.py\", line 651, in from_file\n    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\pydub\\utils.py\", line 60, in _fd_or_path_or_tempfile\n    fd = open(fd, mode=mode)\n         ^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/source/calls/dir2/160588653.wav'", "location": "audio.py - audio_processing"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_util.py\", line 251, in _openfile\n    fileobj = open(filename, \"rb+\" if writable else \"rb\")\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/data/processed_data/160588653.wav'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 41, in add_to_mapping\n    audio_atrs = get_audio_attrs_for_report(audio_path=audio_file_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\audio\\audio.py\", line 125, in get_audio_attrs_for_report\n    duration = get_audio_duration_in_seconds(path= audio_path)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\audio\\audio.py\", line 90, in get_audio_duration_in_seconds\n    audio = WAVE(path)\n           ^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_file.py\", line 48, in __init__\n    self.load(*args, **kwargs)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_util.py\", line 185, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_util.py\", line 154, in wrapper\n    with _openfile(self, filething, filename, fileobj,\n  File \"C:\\Users\\AnshulBhardwaj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\contextlib.py\", line 137, in __enter__\n    return next(self.gen)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_util.py\", line 272, in _openfile\n    raise MutagenError(e)\nmutagen.MutagenError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/data/processed_data/160588653.wav'", "location": "main.py - add_to_mapping"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\adapters\\transcription.py\", line 44, in recognize_from_file\n    conversation_transcriber = speechsdk.transcription.ConversationTranscriber(speech_config=speech_config, audio_config=audio_config)\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\transcription.py\", line 136, in __init__\n    _call_hr_fn(\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 62, in _call_hr_fn\n    _raise_if_failed(hr)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 55, in _raise_if_failed\n    __try_get_error(_spx_handle(hr))\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 50, in __try_get_error\n    raise RuntimeError(message)\nRuntimeError: Exception with error code: \n[CALL STACK BEGIN]\n\n    > pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - recognizer_create_speech_recognizer_from_config\n\n[CALL STACK END]\n\nException with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)", "location": "transcription.py - recognize_from_file"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\adapters\\translator.py\", line 75, in get_translated_transcriptions\n    with open(transcription_jsonPath, 'r', encoding='utf-8') as file:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/data/audio_analytics/160588653/transcript_output.json'", "location": "main.py - get_translated_transcriptions"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured: expected str, bytes or os.PathLike object, not NoneType", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 183, in get_kpis\n    with open(transcription_jsonPath, \"r\", encoding=\"utf-8\") as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nTypeError: expected str, bytes or os.PathLike object, not NoneType", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/data/audio_analytics/160588653/transcript_output.json'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 229, in get_kpis_arabic\n    with open(transciption_jsonpath_arabic, \"r\", encoding=\"utf-8\") as fp:\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/data/audio_analytics/160588653/transcript_output.json'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 304, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\audio\\audio.py\", line 45, in audio_processing\n    sound = AudioSegment.from_mp3(input_path)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\pydub\\audio_segment.py\", line 796, in from_mp3\n    return cls.from_file(file, 'mp3', parameters=parameters)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\pydub\\audio_segment.py\", line 651, in from_file\n    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)\n                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\pydub\\utils.py\", line 60, in _fd_or_path_or_tempfile\n    fd = open(fd, mode=mode)\n         ^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/source/calls/dir2/160675031.wav'", "location": "audio.py - audio_processing"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_util.py\", line 251, in _openfile\n    fileobj = open(filename, \"rb+\" if writable else \"rb\")\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/data/processed_data/160675031.wav'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 41, in add_to_mapping\n    audio_atrs = get_audio_attrs_for_report(audio_path=audio_file_path)\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\audio\\audio.py\", line 125, in get_audio_attrs_for_report\n    duration = get_audio_duration_in_seconds(path= audio_path)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\audio\\audio.py\", line 90, in get_audio_duration_in_seconds\n    audio = WAVE(path)\n           ^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_file.py\", line 48, in __init__\n    self.load(*args, **kwargs)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_util.py\", line 185, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_util.py\", line 154, in wrapper\n    with _openfile(self, filething, filename, fileobj,\n  File \"C:\\Users\\AnshulBhardwaj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\contextlib.py\", line 137, in __enter__\n    return next(self.gen)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\mutagen\\_util.py\", line 272, in _openfile\n    raise MutagenError(e)\nmutagen.MutagenError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\AnshulBhardwaj\\\\Desktop\\\\telecomnew\\\\Telecom%20Egypt%20Internal/data/processed_data/160675031.wav'", "location": "main.py - add_to_mapping"}
{"asctime": "2024-06-08 T15:39:35+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\src\\adapters\\transcription.py\", line 44, in recognize_from_file\n    conversation_transcriber = speechsdk.transcription.ConversationTranscriber(speech_config=speech_config, audio_config=audio_config)\n                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\transcription.py\", line 136, in __init__\n    _call_hr_fn(\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 62, in _call_hr_fn\n    _raise_if_failed(hr)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 55, in _raise_if_failed\n    __try_get_error(_spx_handle(hr))\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\venv\\Lib\\site-packages\\azure\\cognitiveservices\\speech\\interop.py\", line 50, in __try_get_error\n    raise RuntimeError(message)\nRuntimeError: Exception with error code: \n[CALL STACK BEGIN]\n\n    > pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - pal_string_to_wstring\n    - recognizer_create_speech_recognizer_from_config\n\n[CALL STACK END]\n\nException with an error code: 0x8 (SPXERR_FILE_OPEN_FAILED)", "location": "transcription.py - recognize_from_file"}
{"asctime": "2024-06-08 T16:22:23+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:23+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:23+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:24+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:24+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:24+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:26+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:26+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:26+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:27+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:27+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:27+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:29+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:29+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:22:29+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:36+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:36+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:36+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:41+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:41+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:41+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:43+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:43+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:43+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:45+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:45+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:45+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:47+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:47+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:47+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:49+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 201, in get_kpis\n    result[\"summary\"] = summarisation_result[\"summary\"]\n                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:49+0530", "message": "An Error Occured: 'summary'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 245, in get_kpis_arabic\n    arabic_summarisation_result = trans_obj.get_translated_transcriptions_pipeline(eng_summ_result[\"summary\"], \"en\", \"ar-EG\")\n                                                                                   ~~~~~~~~~~~~~~~^^^^^^^^^^^\nKeyError: 'summary'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:36:49+0530", "message": "An Error Occured: 'NoneType' object is not subscriptable", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 308, in pipeline_after_transcription\n    merged_output[\"result\"][\"summary\"] = result[\"summary\"]\n                                         ~~~~~~^^^^^^^^^^^\nTypeError: 'NoneType' object is not subscriptable", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:38:47+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\app.py\", line 28, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\logs\\logger.py\", line 66, in log_Garbage_Collector\n    remove_old_logs_from_top(error_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\logs\\logger.py\", line 58, in remove_old_logs_from_top\n    if not is_log_old(line):\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\logs\\logger.py\", line 44, in is_log_old\n    log_data = json.loads(log_line)\n               ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\decoder.py\", line 340, in decode\n    raise JSONDecodeError(\"Extra data\", s, end)\njson.decoder.JSONDecodeError: Extra data: line 1 column 533 (char 532)", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-06-08 T16:40:47+0530", "message": "An Error Occured ..", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\app.py\", line 28, in Process_Audio_files\n    log_Garbage_Collector()\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\logs\\logger.py\", line 67, in log_Garbage_Collector\n    remove_old_logs_from_top(error_log_path)\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\logs\\logger.py\", line 59, in remove_old_logs_from_top\n    if not is_log_old(line):\n           ^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\logs\\logger.py\", line 44, in is_log_old\n    log_data = json.loads(log_line)\n               ^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\AnshulBhardwaj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\decoder.py\", line 340, in decode\n    raise JSONDecodeError(\"Extra data\", s, end)\njson.decoder.JSONDecodeError: Extra data: line 1 column 533 (char 532)", "location": "App.py - Process_Audio_files"}
{"asctime": "2024-06-08 T16:46:55+0530", "message": "An Error Occured: 'Main' object has no attribute 'merge_sentiment_with_transcription'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 352, in pipeline_after_transcription\n    self.merge_sentiment_with_transcription(\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Main' object has no attribute 'merge_sentiment_with_transcription'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:47:48+0530", "message": "An Error Occured: 'Main' object has no attribute 'merge_sentiment_with_transcription'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 352, in pipeline_after_transcription\n    self.merge_sentiment_with_transcription(\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Main' object has no attribute 'merge_sentiment_with_transcription'", "location": "main.py - pipeline_after_transcription"}
{"asctime": "2024-06-08 T16:48:55+0530", "message": "An Error Occured: 'Main' object has no attribute 'merge_sentiment_with_transcription'", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Users\\AnshulBhardwaj\\Desktop\\telecomnew\\Telecom%20Egypt%20Internal\\main.py\", line 352, in pipeline_after_transcription\n    self.merge_sentiment_with_transcription(\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'Main' object has no attribute 'merge_sentiment_with_transcription'", "location": "main.py - pipeline_after_transcription"}
